# alias eqpt_gui_assets="eqpt_gui_dev && GEM_HOME=/home/jcarson/.gems/eqpt-gui/ruby/3.3.0 GEM_PATH="" PATH=/home/jcarson/.npm-packages/bin:/home/jcarson/.gems/eqpt-gui/ruby/3.3.0/bin:$PATH RAILS_ENV=jcarson_dev ./bin/dev"
alias eqpt_gui_assets="eqpt_gui_dev && RAILS_ENV=jcarson_dev bundle exec ./bin/dev"
alias eqpt_gui_backup_active_storage="eqpt_gui_dev && RAILS_ENV=jcarson_backup bundle exec rake eqpt_gui:backup:active_storage"
alias eqpt_gui_backup_database="eqpt_gui_dev && RAILS_ENV=jcarson_backup bundle exec rake eqpt_gui:backup:database"
alias eqpt_gui_billing_link="eqpt_gui_dev && RAILS_ENV=jcarson_dev bundle exec rake billing:sync:addresses"
alias eqpt_gui_console="eqpt_gui_dev && bundle exec rails console -e jcarson_dev"
alias eqpt_gui_debug_server="eqpt_gui_dev && ./bin/rails server -e jcarson_dev -b 127.0.0.1 -u puma"
alias eqpt_gui_deploy="ruby3 && __cap_deploy__ orderapp /home/orderapp/git_clones/eqpt-gui"
alias eqpt_gui_delayed="eqpt_gui_dev && RAILS_ENV=jcarson_dev bin/delayed_job --exit-on-complete run"
alias eqpt_gui_delayed_view="eqpt_gui_dev && mysql eqpt_gui_jcarson_dev --batch --skip-column-names -e \"SELECT handler FROM delayed_jobs;\" | /home/jcarson/git_clones/work-scripts/mtt/development/format_delayed_job.rb"
alias eqpt_gui_dev="ruby3 && cd /home/jcarson/git_clones/eqpt-gui && __echo_dev_name__ EqptGuiDev"
alias eqpt_gui_db="eqpt_gui_dev && mysql eqpt_gui_jcarson_dev"
alias eqpt_gui_force_compile_js="eqpt_gui_dev && RAILS_ENV=jcarson_dev bundle exec yarn build"
alias eqpt_gui_force_compile_css="eqpt_gui_dev && RAILS_ENV=jcarson_dev bundle exec yarn build:css"

# (e)qpt (g)ui (g)rep
alias egg="eqpt_gui_dev && __eqpt_gui_grep__"

alias eqpt_gui_log="eqpt_gui_dev && tail -f ./log/jcarson_dev.log"
alias eqpt_gui_log_jcarson="eqpt_gui_dev && tail -f log/jcarson_dev.log | grep 'JCARSON'"
alias eqpt_gui_log_req="eqpt_gui_dev && tail -f log/jcarson_dev.log | grep -B 1 -A 1 'Processing by'"
alias eqpt_gui_reconcile="eqpt_gui_dev && RAILS_ENV=jcarson_dev bundle exec rake eqpt_gui:config:missing_equipment_category_permissions_for_users eqpt_gui:config:unconfigured_controller_actions eqpt_gui:config:unconfigured_authorization_aliases"
alias eqpt_gui_restart="eqpt_gui_dev && RAILS_ENV=jcarson_dev bundle exec rake restart"
alias eqpt_gui_restore_database_from_backups="eqpt_gui_dev && RAILS_ENV=jcarson_dev bundle exec rake eqpt_gui:restore:database[jcarson_backup]"
alias eqpt_gui_restore_active_storage_from_backups="eqpt_gui_dev && RAILS_ENV=jcarson_dev bundle exec rake eqpt_gui:restore:active_storage[jcarson_backup]"
alias eqpt_gui_rma_link="eqpt_gui_dev && RAILS_ENV=jcarson_dev bundle exec rake rma:sync:insert_and_assign"
alias eqpt_gui_routes="eqpt_gui_dev && RAILS_ENV=jcarson_dev bundle exec rails routes"
alias eqpt_gui_seed="eqpt_gui_dev && RAILS_ENV=jcarson_dev bundle exec rake eqpt_gui:seed:seed_development_from_production"
alias eqpt_gui_test_run="eqpt_gui_dev && RAILS_ENV=test bundle exec rake eqpt_gui:test:run"
alias eqpt_gui_test_schema_dump="eqpt_gui_dev && RAILS_ENV=jcarson_dev bundle exec rake eqpt_gui:test:dump_aux_db_schemas"
alias eqpt_gui_travis_run="eqpt_gui_dev && RAILS_ENV=travis bundle exec rake eqpt_gui:test:run"
