alias mtt_ai_agi_console="mtt_ai_dev && ./script/console.sh -t agi"
alias mtt_ai_agi_server="mtt_ai_dev && ./script/agi_server.sh"
alias mtt_ai_dev="ruby2 && cd ~/git_clones/mtt-ai"
alias mtt_ai_console="mtt_ai_dev && ./script/console.sh"
alias mtt_ai_test="mtt_ai_dev && MTT_AI_ENV=test bundle exec rake mtt_ai:test:run"
