function __system_upgrade_help__ {
  echo -e "After upgrading Arch with pacman -Syu, you may need to do the following:"

  echo -e "  - \033[0;32mRecompile openssh\033[0;0m"
  echo -e "    - cd ~/sources/openssh-9.0p1"
  echo -e "    - make clean"
  echo -e "    - ./configure --prefix=/usr/local/openssh/openssh-9.0p1"
  echo -e "    - make"
  echo -e "    - sudo make install"

  echo -e ""
  echo -e "  - \033[0;32mRecompile passenger for ruby2 and ruby3\033[0;0m"
  echo -e "    - hpbxgui_dev"
  echo -e "    - ruby2"
  echo -e "    - recompile_passenger"
  echo -e "    - eqpt_gui_dev"
  echo -e "    - ruby3"
  echo -e "    - recompile_passenger"

  echo -e ""
  echo -e "  - \033[0;32mUpdate /usr/lib/systemd/system/httpd.service\033[0;0m"
  echo -e "    [Unit]"
  echo -e "    Description=Apache Web Server"
  echo -e "    After=network.target remote-fs.target nss-lookup.target"
  echo -e ""
  echo -e "    [Service]"
  echo -e "    Type=simple"
  echo -e "    ExecStart=/usr/bin/httpd -k start -DFOREGROUND -DRuby2"
  echo -e "    ExecStop=/usr/bin/httpd -k graceful-stop"
  echo -e "    ExecReload=/usr/bin/httpd -k graceful"
  echo -e "    PrivateTmp=true"
  echo -e "    LimitNOFILE=infinity"
  echo -e "    KillMode=mixed"
  echo -e "    Environment=LD_LIBRARY_PATH=/usr/local/ImageMagick/6.9.12-34/lib"
  echo -e ""
  echo -e "    [Install]"
  echo -e "    WantedBy=multi-user.target"
}

alias upgrade_help="__system_upgrade_help__"
