alias tickets_assets="tickets_dev && RAILS_ENV=jcarson_dev bundle exec rake assets:precompile"
alias tickets_console="tickets_dev && RAILS_ENV=jcarson_dev bin/rails console"
alias tickets_credentials_edit="tickets_dev && EDITOR=vim bin/rails credentials:edit --environment jcarson_dev"
alias tickets_credentials_show="tickets_dev && bin/rails credentials:show --environment jcarson_dev"
alias tickets_db="tickets_dev && sqlite3 /home/jcarson/.app-data/tickets/storage/jcarson_dev.sqlite3"
alias tickets_db_migrate="tickets_dev && RAILS_ENV=jcarson_dev bundle exec rake db:migrate"
alias tickets_db_migrate_status="tickets_dev && RAILS_ENV=jcarson_dev bundle exec rake db:migrate:status"
alias tickets_dev="ruby4 && cd ~/git_clones/tickets && __echo_dev_name__ TicketsDev"
alias tickets_dump_schema="tickets_dev && RAILS_ENV=jcarson_dev SCHEMA=db/jcarson_dev_schema.rb bin/rails db:schema:dump:primary"
alias tickets_ensure_schema_uptodate="tickets_db_migrate && tickets_dump_schema"
alias tickets_load_schema="tickets_dev && RAILS_ENV=jcarson_dev SCHEMA=db/jcarson_dev_schema.rb bin/rails db:schema:load:primary"
alias tickets_log="tickets_dev && tail -f ./log/jcarson_dev.log"
alias tickets_jcarson_seed="tickets_dev && RAILS_ENV=jcarson_dev bundle exec rake jcarson_dev:seed"
alias tickets_reset_db="mysql8 -e 'DROP DATABASE tickets_jcarson_dev; CREATE DATABASE tickets_jcarson_dev;'"
alias tickets_seed="tickets_dev && RAILS_ENV=jcarson_dev bin/rails db:seed"
alias tickets_web="__activate_webapp__ tickets"
alias tickets_total_reset_db="tickets_reset_db && tickets_load_schema && tickets_seed && tickets_jcarson_seed"
